-- Add comprehensive list of Nigerian college courses
-- Inserting uniquely to prevent duplicates

INSERT INTO university_courses (name)
SELECT name FROM (VALUES
  ('Mechanical Engineering'),
  ('Metallurgical Engineering'),
  ('Marine Engineering'),
  ('Production Engineering'),
  ('Chemical Engineering'),
  ('System Engineering'),
  ('Computer Engineering'),
  ('Material engineering'),
  ('Petroleum and Gas Engineering'),
  ('Structural Engineering'),
  ('Electrical Engineering'),
  ('Electronic Engineering'),
  ('Electrical/Electronic Engineering'),
  ('Civil Engineering'),
  ('Agricultural and Bio resources Engineering'),
  ('Pure chemistry'),
  ('Geology'),
  ('Mathematics'),
  ('Physics'),
  ('Statistics'),
  ('Geophysics'),
  ('Private and Public law'),
  ('International and jurisprudence law'),
  ('Commercial and property law'),
  ('Veterinary surgery'),
  ('Veterinary Anatomy'),
  ('Veterinary Medicine'),
  ('Veterinary Physiology'),
  ('Animal Health and production'),
  ('Veterinary teaching hospital'),
  ('Veterinary Pharmacology'),
  ('Veterinary parapsychology and entomology'),
  ('Veterinary obstetrics and reproductive diseases'),
  ('Veterinary pathology and Microbiology'),
  ('Mass Communications'),
  ('Theater and Film studies'),
  ('History and International studies'),
  ('Foreign languages and literature'),
  ('Archeology and Tourism'),
  ('English and Literary studies'),
  ('Fine and Applied arts'),
  ('Linguistics and Nigerian languages'),
  ('Arabic and Islamic studies'),
  ('Christian Religious Studies'),
  ('Music'),
  ('Agriculture Economics'),
  ('Soil Science'),
  ('Animal Science'),
  ('Food and science Technology'),
  ('Agriculture'),
  ('Crop Science'),
  ('Forestry'),
  ('Nutrition and Dietics'),
  ('Agronomy'),
  ('Fisheries'),
  ('Agriculture Extension'),
  ('Biochemistry'),
  ('Microbiology'),
  ('Zoology'),
  ('Botany'),
  ('Cell Biology and Genetics'),
  ('Marine Biology'),
  ('Architecture'),
  ('Geomatics'),
  ('Estate Management'),
  ('Urban and Regional Planning'),
  ('Geoinformatics and surveying'),
  ('Quantity Surveying'),
  ('Child Dental Health'),
  ('Preventive Dentistry'),
  ('Restorative Denstistry'),
  ('Oral And Maxillofacial Surgery'),
  ('Banking and Finance'),
  ('Accounting'),
  ('Marketing'),
  ('Insurance'),
  ('Business Management'),
  ('Industrial relations and Personal management'),
  ('Hospitality and Management'),
  ('Business Administration'),
  ('Hospitality and Tourism'),
  ('Pharmaceutics'),
  ('Pharmacognosy'),
  ('Physiotherapy'),
  ('Clinical Pharmacy and Pharmacy Management'),
  ('Pharmacology and Toxicology'),
  ('Pharmaceutical Chemistry and Industrial Pharmacy'),
  ('Pharmaceutical Technology and Industrial Pharmacy'),
  ('Economics'),
  ('Geography'),
  ('Religion'),
  ('Social work'),
  ('Psychology'),
  ('Sociology and Anthropology'),
  ('Political Science'),
  ('Public Administration and Local Government'),
  ('Philosophy'),
  ('Education and Mathematics'),
  ('Education and Accountancy'),
  ('Education Foundations'),
  ('Science Education'),
  ('Library and Information Science'),
  ('Social Science Education'),
  ('Education and Chemistry'),
  ('Education and Biology'),
  ('Health and Physical Education'),
  ('Education and English Language'),
  ('Education and Political Science'),
  ('Educational Psychology/Guidance and Counselling'),
  ('Education and Geography/physics'),
  ('Education and french'),
  ('Igbo linguistics'),
  ('Adult Education and Extra Mural studies'),
  ('Arts Education'),
  ('Education and Computer Science'),
  ('Vocational and Technical Education'),
  ('Education and religious Studies'),
  ('Education and Social Science'),
  ('Anesthesia'),
  ('Anatomy'),
  ('Psychological Medicine'),
  ('Community Medicine'),
  ('Chemical Pathology'),
  ('Physiology'),
  ('Radiation Medicine'),
  ('Hematology and Immunology'),
  ('Dermatology'),
  ('Medical Biochemistry'),
  ('Medical Microbiology'),
  ('Pediatrics'),
  ('Pharmacology and Therapeutics'),
  ('Medicine'),
  ('Morbid Anatomy'),
  ('Obstetrics and Gynecology'),
  ('Otolaryngology'),
  ('Opthalmology'),
  ('Nursing Science'),
  ('Health Administration and Management'),
  ('Medical rehabilitation'),
  ('Medical Laboratory Science'),
  ('Medical Radiography and Radiological Science')
) AS v(name)
WHERE NOT EXISTS (
  SELECT 1 FROM university_courses WHERE university_courses.name = v.name
);
